- name: Integration test runner
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load the vars
      ansible.builtin.include_vars:
        file: ../../resources/vars/vars.yml

    - name: Check if the common state file exists
      ansible.builtin.stat:
        path: "{{ common_state_file }}"
      register: common_state_stat

    - name: Load the common state file
      ansible.builtin.include_vars:
        file: "{{ common_state_file }}"
        name: common_state
      when: common_state_stat.stat.exists

    - name: Run the the default prepare
      ansible.builtin.include_tasks:
        file: ../task_files/prepare.yml
      when: not common_state.prepared | default(false)
