# see https://github.com/ansible-community/devtools
# but cannot use v prefix for version

name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
# Use '-' instead of '*' for unordered list to match prettier behavior
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
categories:
  - title: "Major Changes"
    labels:
      - "major" # c6476b
  - title: "Minor Changes"
    labels:
      - "feature" # 006b75
      - "enhancement" # ededed
      - "refactoring"
  - title: "Bugfixes"
    labels:
      - "bug" # fbca04
  - title: "Deprecations"
    labels:
      - "deprecated" # fef2c0
exclude-labels:
  - "bot:chronographer:skip"
  - "skip-changelog"
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645942909
  - search: '/(?:and )?@(pre-commit-ci|dependabot)(?:\[bot\])?,?/g'
    replace: ""
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
      - "refactoring"
  patch:
    labels:
      - "patch"
      - "bug"
      - "deprecated"
  default: patch
exclude-contributors:
  - "dependabot"
  - "pre-commit-ci"
autolabeler:
  - label: "skip-changelog"
    title:
      - "/pre-commit autoupdate/"
    body:
      - "/type: chore/i"
    branch:
      - "/^chore/i"
  - label: "bug"
    branch:
      - "/^fix/i"
    body:
      - "/type: fix/i"
  - label: "feature"
    title:
      - "/^(feat|feature)/i"
    body:
      - "/type: feature/i"
  - label: "deprecated"
    title:
      - "/^deprecat(ed|ion)/i"
    body:
      - "/type: deprecat(ed|ion)/i"
template: |
  $CHANGES

