---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.utils": ">=3.0.0"
license_file: LICENSE
name: scm
namespace: ansible
description: A collection of scm utilities
readme: README.md
repository: https://github.com/ansible-collections/ansible.scm
issues: https://github.com/ansible-collections/ansible.scm/issues
tags:
  - application
  - cloud
  - database
  - infrastructure
  - linux
  - monitoring
  - networking
  - security
  - storage
  - tools
  - windows
version: 3.0.0
build_ignore:
  - .github
  - .gitignore
  - .isort.cfg
  - .pre-commit-config.yaml
  - mypy.ini
  - pyproject.toml
  - tox.ini
  - toxfile.py
  - .vscode
