---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.utils": "*"
license_file: LICENSE
name: scm
namespace: ansible
description: A collection of scm utilities
readme: README.md
repository: https://github.com/ansible-collections/ansible.scm
issues: https://github.com/ansible-collections/ansible.scm/issues
tags: []
version: null
