---
- name: include roles
  block:
    - name: "Integration test: {{ item }}"
      ansible.builtin.include_role:
        name: "{{ item }}"
  rescue:
    - name: Report target failure
      set_fact:
        integration_target_failures: "{{ integration_target_failures + [item.split('/')[-1]] }}"