platforms:
  - name: na

provisioner:
  name: ansible
  playbooks:
    destroy: ../resources/playbooks/noop.yml
    prepare: ../resources/playbooks/noop.yml

scenario:
  create_sequence:
    - create
  test_sequence:
    - prepare
  destroy_sequence:
    - destroy
