platforms:
  - name: na

provisioner:
  name: ansible
  playbooks:
    cleanup: ../_resources/playbooks/noop.yml
    converge: ../_resources/playbooks/converge.yml
    destroy: ../_resources/playbooks/noop.yml
    prepare: ../_resources/playbooks/prepare.yml

scenario:
  test_sequence:
    - prepare
    - converge
  destroy_sequence:
    - destroy
