# Some tests require secrets from the repo
# and therefore require an approval/label to run

name: auto-label

on:
  pull_request_target:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove the 'safe to test' label
        run: gh pr edit $PR_NUMBER --remove-label "safe to test"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}
        if: >-
          contains(github.event.pull_request.labels.*.name, 'safe to test')

      - name: Check if the PR author is a collaborator
        run: 'gh api -H "Accept: application/vnd.github.v3+json" $API_URL'
        env:
          API_URL: /repos/${{ github.repository }}/collaborators/${{ github.actor }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Only if the check passed, set the label
        run: gh pr edit $PR_NUMBER --add-label "safe to test"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}
