# Some tests require secrets from the repo
# and therefore require an approval/label to run

name: privileged

concurrency:
  group: ${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [main]
    types: [labeled]
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "::notice label detected::Approved, safe to test"
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

  integration:
    needs:
      - approval
    uses: ansible-network/github_actions/.github/workflows/integration_simple.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  privileged_ok:
    if: ${{ always() }}
    needs:
      - integration
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.integration.result }}',
          ]) == {'success'}"
